### ISSUE TITLE
Support using outputs as templating variables for PR and commits

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/tool-versions-update-action#150]
## Summary

The actions in this project now output some information (#62) about the execution which might be used in commit messages (#13, #22) or Pull Request titles/descriptions (#12). However, when using the [batteries included actions](https://github.com/ericcornelissen/tool-versions-update-action/tree/74adf96aa7cf65537a8d94119db4fa03d2e9c132#batteries-included) the Action outputs can't be used in the `commit-message`/`pr-description`/`pr-title` inputs. This would be useful because it would allow for including contextual information in these fields.

## Idea

I'm thinking that adopting a templating format similar to [GitHub Action expressions](https://docs.github.com/en/actions/learn-github-actions/expressions) would make sense, which would substitute outputs into the provided string.

For example, the following configuration

```yml
- uses: ericcornelissen/tool-versions-update-action/pr@v0
  with:
    max: 1
    pr-title: Bump {{updated-tools}}
```

would results in Pull Requests with titles such as "Bump actionlint" or "Bump shellcheck".
