### ISSUE TITLE
Add support for non-Pull Request update workflows

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/tool-versions-update-action#2]
## Summary

As of [v0.1.0](https://github.com/ericcornelissen/tool-versions-update-action/releases/tag/v0.1.0) it is only possible to use this action to create a Pull Request with updates. This should probably be extended to support other workflows as well.

### Workflows

_If you have a suggestion, please comment or open a new issue._

- [x] Pull Request
- [ ] Commit

### What it could look like

Support multiple preset workflows, from the user's perspective this would look like:

```yaml
# Create a Pull Request with updates
- uses: ericcornelissen/tool-versions-update-action/pr@vX.Y.Z
  with:
    max: 1

# Create and push a commit with updates
- uses: ericcornelissen/tool-versions-update-action/commit@vX.Y.Z
  with:
    branch: main # Example: would commit the updates to main

# etc...
```
