### ISSUE TITLE
Support filtering what tools are updated

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/tool-versions-update-action#7]
## Summary

Add new options that allows users to list the tools that can be updated. This could be used to update a specific tool, use a [matrix](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) of tools to update, create update groups (e.g. update tooling related to X), or exclude certain tools that shouldn't be updated for whatever reason.

### Suggestion

Add two new options:

1. `only` which lists tools that can be considered for updates - all other tools won't be updated
2. `not` which lists tools that cannot be considered for updates - all other tools may be updated

#### Interaction with other options

- `max`: can be combined with both `only` and `not` just fine, even if some combinations of values don't make sense (e.g. `only: actionlint` with `max: 2`).
- `only` and `not` should be mutually exclusive.

#### Examples

Only update one tool:

```yaml
- uses: ericcornelissen/tool-versions-update-action@v0.1.0
  with:
    only: actionlint
```

Only update tooling related to shell scripts:

```yaml
- uses: ericcornelissen/tool-versions-update-action@v0.1.0
  with:
    only: |-
      shellcheck
      shfmt
```

Don't update a particular tool:

```yaml
- uses: ericcornelissen/tool-versions-update-action@v0.1.0
  with:
    not: yamllint
```
